site_name: Notes
site_author: Litreily
site_description: Note Everything
site_url: http://www.litreily.top/Notes/
repo_url: https://github.com/Litreily/Notes
edit_uri: tree/mkdocs/docs/

copyright: Copyright &copy; 2020 LITREILY

theme:
  name: material
  # custom_dir:
  # favicon: 
  icon:
    logo: material/book-open-page-variant
  features:
    - tabs
  palette:
    scheme: 'default'
    primary: 'blue grey'
    accent: 'indigo'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  # - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.snippets:
  #     check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/litreily
extra_css:
  - css/extra.css
extra_javascript:

nav:
  - Introduction: index.md
  - Aphorisms: aphorisms.md
  - Book List: books.md
  - Favorites: favorites.md
  - Commands:
    - cd: commands/cd.md
    - df: commands/df.md
    - du: commands/du.md
    - fc-cahe: commands/fc-cache.md
    - ifconfig: commands/ifconfig.md
    - ip: commands/ip.md
    - ls: commands/ls.md
    - lsb_release: commands/lsb_release.md
    - man: commands/man.md
    - mkdir: commands/mkdir.md
    - mksquashfs: commands/mksquashfs.md
    - mount: commands/mount.md
    - ping: commands/ping.md
    - pwd: commands/pwd.md
    - rm: commands/rm.md
    - sar: commands/sar.md
    - sed: commands/sed.md
    - sudo: commands/sudo.md
    - xargs: commands/xargs.md
  - Linux C: 
    - Linux: linux/README.md
    - Preprocessor: linux/preprocessor.md
    - Keywords: linux/keywords.md
    - Kernel: 
      - Ftrace: linux/kernel/ftrace.md
      - Watchdog: linux/kernel/watchdog.md
  - Network: 
    - Protocol: 
      - Protocol: network/protocol.md
      - Link layer: network/linkLayer.md
      - IP: network/ip.md
      - ARP: network/arp.md
      - ICMP: network/icmp.md
    - Proxy: 
      - Proxy: network/proxy.md
      - Cntlm: network/cntlm.md
      - Proxychains4: network/proxychains4.md
      - ShadowSocks: network/shadowsocks.md
    - Tools:
      - iperf: network/iperf.md
      - tc: network/tc.md
      - Wireshark: network/wireshark.md
    - Apps: 
      - samba: network/samba.md
      - tftp: network/tftp.md
  - OS:
    - Ubuntu:
      - Add user: os/ubuntu/userAdd.md
      - AWS EC2: os/ubuntu/aws_ec2.md
      - FAQ: os/ubuntu/faq.md
      - Installer: os/ubuntu/installer.md
      - Shell: os/ubuntu/shell.md
      - Shell scripts: os/ubuntu/shellScripts.md
      - Themes: os/ubuntu/themes.md
      - VPS: os/ubuntu/vps.md
    - Windows:
      - PowerShell: os/windows/powershell.md
      - CMD: os/windows/cmd.md
      - FAQ: os/windows/faq.md
  - Python: 
    - general: 
      - General: python/install.md
      - Decorator: python/decorator.md
      - Generator: python/generator.md
      - Iterator: python/iterator.md
      - Lambda: python/lambda.md
    - Download: python/download.md
    - NIC: python/nic.md
  - Software:
    - Atom: software/atom.md
    - Chrome: software/chrome.md
    - Docker: software/docker.md
    - Git: software/git.md
    - Gitbook: software/gitbook.md
    - Hexo: software/hexo.md
    - Nodejs: software/nodejs.md
    - Cscope: software/cscope.md
    - Teraterm: software/teraterm.md
    - Tex: software/tex.md
    - Tmux: software/tmux.md
    - VIM: software/vim.md
    - VSCode: software/vsc.md
    - Database: 
      - MongoDB: db/mongodb.md
  - Web: 
    - CSS: web/css.md
    - LNMP: web/LNMP.md
  - Appendix:
    - ASCII: appendix/ascii.md
    - GSM: appendix/gsm.md
    - Tools:
      - common: appendix/tools/common.md
      - network: appendix/tools/network.md
      - programming: appendix/tools/programming.md
